### PR TITLE
Vertex colors, weights and new normal map detection hack.

### PR DESCRIPTION
**Pull request by angavrilov**
I felt like playing with this again today, so here are some new fixes for VC1:

* Supported importing vertex colors, and more UV maps.
* Fixed handing of the third vertex weight.
* Implemented a normal map detection hack based on testing the colors in the image itself.

### CODE REVIEW

**Comment by gomtuu** [comment]
Thanks! I'll take a look!

**Comment by angavrilov** [comment]
By the way, do you plan to switch to blender 2.8, or at least support importing as Cycles materials (Blender Render is removed in 2.8)?

**Comment by gomtuu** [comment]
Blender 2.80 is on my radar, but I haven't put any effort into that yet. I created an [issue](https://github.com/gomtuu/import_valkyria/issues/9) for it just now.

**Comment by angavrilov** [comment]
This pull request fixes #7 btw, and works around #3 by looking at the image itself as a simpler solution.

**Comment by angavrilov** [comment]
This weekend I've been experimenting with re-creating the in-game shading appearance in Blender 2.8 with Eevee for viewport and Cycles+Freestyle+Compositor for render, and it seems to work quite well: https://imgur.com/a/e30kQdj

To easily grab the necessary shading mask textures, I added a way to import just a stand-alone HTX file to the addon; since it's a corner case use I didn't officially add the extension, and you have to disable filter to select files.

**Pull request closed without merging**
